on: push
name: Snap
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_snap:
    name: craft
    runs-on: ubuntu-18.04 # FIXME: https://github.com/samuelmeuli/action-snapcraft/issues/24
    steps:
    - uses: actions/checkout@v2

    - uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true

    - name: Build snap
      run: sg lxd -c 'snapcraft --use-lxd'

    - uses: actions/upload-artifact@v2
      with:
        name: snapped
        path: '*.snap'
        if-no-files-found: error
